environment:
  matrix:
    - PYTHON_VERSION: "3.5"
      MINICONDA: "C:\\Miniconda35"
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda36"
    - PYTHON_VERSION: "3.7"
      MINICONDA: "C:\\Miniconda36"
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda create -q -n test-environment python=%PYTHON_VERSION% scipy>=0.19.0 numpy>=1.15.4"
  - "activate test-environment"
  - "pip install hypothesis"
  - "pip install pytest"
build: off
test_script:
  - "python setup.py install"
  - "pytest ."
  - "python doctests.py" 
