environment:
  matrix:
    - PYTHON: "C:\\Python35"
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build: off
test_script:
  - "%PYTHON%\\python.exe setup.py test"
  - "%PYTHON%\\python.exe -m pip install nashpy"
