name: nash
channels:
- defaults
dependencies:
- libgfortran=3.0.0=1
- mkl=2017.0.1=0
- numpy=1.13.0=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- python=3.5.3=1
- readline=6.2=2
- scipy=0.19.0=np113py35_0
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
prefix: /home/vince/anaconda3/envs/nash

